### ISSUE TITLE
Amazon AWS

### ISSUE THREAD

**Issue by Natali-Oliinyk-qa** [dedicatted/DedicattedZen#147] opened 2022-11-04 11:50 UTC
- [ ] after clicking "See less", the user must return to the Amazon AWS form (see more)

![less text.gif](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/0ffeed8b-b8f6-4fea-849f-d214cb83dc77)

### **the same problem on these pages :**
- Google Cloud
- Microsoft Azure
- Kubernetes
- DevOps-As-A-Service
- Cloud migration consulting
- cloud infrastructure and designe

**Comment by KostiaLevchenko** [comment] 2022-11-07 09:14
duplicate of issee#143

**Closed as completed by KostiaLevchenko** 2022-11-07 09:14 UTC
Labels: bug, Frontend
